// ============================================================================
// EcoRoute AI — Comprehensive Database Seed Script
// Configurable Multi-Provider Model Catalog
// ============================================================================

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding configurable multi-provider AI model catalog...');

  // ==========================================================================
  // 1. AI Providers
  // ==========================================================================
  const providersData = [
    {
      name: 'OpenAI',
      providerKey: 'openai',
      slug: 'openai',
      adapterType: 'openai_compatible',
      baseUrl: 'https://api.openai.com/v1',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.OPENAI_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://api.openai.com/v1' }),
    },
    {
      name: 'Google Gemini',
      providerKey: 'google_gemini',
      slug: 'google_gemini',
      adapterType: 'google_gemini',
      baseUrl: 'https://generativelanguage.googleapis.com',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.GOOGLE_GEMINI_API_KEY || process.env.GOOGLE_AI_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://generativelanguage.googleapis.com' }),
    },
    {
      name: 'Anthropic',
      providerKey: 'anthropic',
      slug: 'anthropic',
      adapterType: 'anthropic',
      baseUrl: 'https://api.anthropic.com',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.ANTHROPIC_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://api.anthropic.com' }),
    },
    {
      name: 'Groq',
      providerKey: 'groq',
      slug: 'groq',
      adapterType: 'openai_compatible',
      baseUrl: 'https://api.groq.com/openai/v1',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.GROQ_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://api.groq.com/openai/v1' }),
    },
    {
      name: 'DeepSeek',
      providerKey: 'deepseek',
      slug: 'deepseek',
      adapterType: 'openai_compatible',
      baseUrl: 'https://api.deepseek.com/v1',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.DEEPSEEK_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://api.deepseek.com/v1' }),
    },
    {
      name: 'Together AI',
      providerKey: 'together',
      slug: 'together',
      adapterType: 'openai_compatible',
      baseUrl: 'https://api.together.xyz/v1',
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: process.env.TOGETHER_API_KEY ? 'CONFIGURED' : 'MISSING_CREDENTIALS',
      configJson: JSON.stringify({ baseUrl: 'https://api.together.xyz/v1' }),
    },
    {
      name: 'Ollama (Local)',
      providerKey: 'ollama',
      slug: 'ollama',
      adapterType: 'openai_compatible',
      baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434/v1',
      status: 'ACTIVE',
      healthStatus: 'UNKNOWN',
      configurationStatus: 'CONFIGURED',
      configJson: JSON.stringify({ baseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434/v1' }),
    },
    {
      name: 'Mock Provider',
      providerKey: 'mock',
      slug: 'mock',
      adapterType: 'mock',
      baseUrl: null,
      status: 'ACTIVE',
      healthStatus: 'HEALTHY',
      configurationStatus: 'CONFIGURED',
      configJson: JSON.stringify({ description: 'High-fidelity simulation engine for offline testing' }),
    },
  ];

  const providerMap = new Map<string, string>();

  for (const p of providersData) {
    const provider = await prisma.aIProvider.upsert({
      where: { providerKey: p.providerKey },
      update: {
        name: p.name,
        slug: p.slug,
        adapterType: p.adapterType,
        baseUrl: p.baseUrl,
        healthStatus: p.healthStatus,
        configurationStatus: p.configurationStatus,
        configJson: p.configJson,
      },
      create: p,
    });
    providerMap.set(p.providerKey, provider.id);
  }

  console.log(`  ✓ Created/updated ${providersData.length} AI providers`);

  // Helper for capability object + list
  const makeCaps = (opts: {
    textGeneration?: boolean;
    reasoning?: boolean;
    coding?: boolean;
    mathematics?: boolean;
    vision?: boolean;
    toolCalling?: boolean;
    structuredOutput?: boolean;
    longContext?: boolean;
    translation?: boolean;
    creativeWriting?: boolean;
    analysis?: boolean;
    summarization?: boolean;
  }) => {
    const list: string[] = ['text_generation'];
    if (opts.coding) list.push('code_generation');
    if (opts.analysis !== false) list.push('analysis');
    if (opts.creativeWriting !== false) list.push('creative_writing');
    if (opts.summarization !== false) list.push('summarization');
    if (opts.mathematics) list.push('math');
    if (opts.reasoning) list.push('reasoning');
    if (opts.translation) list.push('translation');
    if (opts.vision) list.push('vision');

    return {
      capabilities: list,
      flags: {
        textGeneration: true,
        reasoning: !!opts.reasoning,
        coding: !!opts.coding,
        mathematics: !!opts.mathematics,
        vision: !!opts.vision,
        toolCalling: opts.toolCalling !== false,
        structuredOutput: opts.structuredOutput !== false,
        longContext: !!opts.longContext,
      },
    };
  };

  // ==========================================================================
  // 2. Initial Model Catalog
  // ==========================================================================
  const modelsData = [
    // ---- OpenAI Models ----
    {
      providerKey: 'openai',
      modelKey: 'gpt-4o',
      providerModelId: 'gpt-4o',
      displayName: 'GPT-4o',
      family: 'gpt-4',
      version: '2024-11-20',
      description: 'Flagship omni model, high multimodal reasoning and mathematical performance.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 2.50, outputPricePerMillionTokens: 10.00, cachedInputPerMillionTokensUsd: 1.25, currency: 'USD' },
      performance: { estimatedLatencyMs: 800, tokensPerSecond: 85 },
      env: { energyPerMillionTokensWh: 400, carbonGramsPerMillionTokens: 160, confidence: 'medium', source: 'EMNLP 2024 / Sustainable Computing 2023' },
      tags: ['flagship', 'multimodal', 'vision', 'math-leader'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'gpt-4o-mini',
      providerModelId: 'gpt-4o-mini',
      displayName: 'GPT-4o Mini',
      family: 'gpt-4',
      version: '2024-07-18',
      description: 'Affordable, low-latency compact frontier model for high-throughput tasks.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 0.15, outputPricePerMillionTokens: 0.60, cachedInputPerMillionTokensUsd: 0.075, currency: 'USD' },
      performance: { estimatedLatencyMs: 350, tokensPerSecond: 130 },
      env: { energyPerMillionTokensWh: 150, carbonGramsPerMillionTokens: 60, confidence: 'medium', source: 'EMNLP 2024 / Sustainable Computing 2023' },
      tags: ['fast', 'cost-effective', 'multimodal'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'gpt-4.1',
      providerModelId: 'gpt-4.1',
      displayName: 'GPT-4.1',
      family: 'gpt-4.1',
      version: '2025-01',
      description: 'Next-generation general-purpose model with enhanced instruction adherence.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 256000,
      maxOutputTokens: 32768,
      pricing: { inputPricePerMillionTokens: 3.00, outputPricePerMillionTokens: 12.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 900, tokensPerSecond: 90 },
      env: { energyPerMillionTokensWh: 420, carbonGramsPerMillionTokens: 168, confidence: 'medium', source: 'Published Research' },
      tags: ['next-gen', 'reasoning', 'coding'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'gpt-4.1-mini',
      providerModelId: 'gpt-4.1-mini',
      displayName: 'GPT-4.1 Mini',
      family: 'gpt-4.1',
      version: '2025-01',
      description: 'High-speed compact model from the 4.1 series with balanced accuracy.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 0.20, outputPricePerMillionTokens: 0.80, currency: 'USD' },
      performance: { estimatedLatencyMs: 400, tokensPerSecond: 125 },
      env: { energyPerMillionTokensWh: 160, carbonGramsPerMillionTokens: 64, confidence: 'medium', source: 'Published Research' },
      tags: ['fast', 'balanced'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'gpt-4.1-nano',
      providerModelId: 'gpt-4.1-nano',
      displayName: 'GPT-4.1 Nano',
      family: 'gpt-4.1',
      version: '2025-01',
      description: 'Ultra-lightweight edge model for classification, extraction, and sub-second triage.',
      caps: makeCaps({ coding: false, mathematics: false, structuredOutput: true }),
      contextWindow: 32000,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.05, outputPricePerMillionTokens: 0.20, currency: 'USD' },
      performance: { estimatedLatencyMs: 180, tokensPerSecond: 180 },
      env: { energyPerMillionTokensWh: 70, carbonGramsPerMillionTokens: 28, confidence: 'high', source: 'Estimated for nano tier' },
      tags: ['ultra-fast', 'ultra-green', 'edge'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'o3',
      providerModelId: 'o3',
      displayName: 'OpenAI o3',
      family: 'o-series',
      version: '2025-01',
      description: 'Frontier reasoning model utilizing deep chain-of-thought for competitive programming and math.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, structuredOutput: true, longContext: true }),
      contextWindow: 200000,
      maxOutputTokens: 100000,
      pricing: { inputPricePerMillionTokens: 10.00, outputPricePerMillionTokens: 40.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 3500, tokensPerSecond: 45 },
      env: { energyPerMillionTokensWh: 950, carbonGramsPerMillionTokens: 380, confidence: 'medium', source: 'Extrapolated for reasoning compute' },
      tags: ['deep-reasoning', 'competition-math', 'complex-logic'],
      isDefault: false,
    },
    {
      providerKey: 'openai',
      modelKey: 'o4-mini',
      providerModelId: 'o4-mini',
      displayName: 'OpenAI o4-mini',
      family: 'o-series',
      version: '2025-02',
      description: 'Fast mathematical reasoner optimized for science and code debugging with lower latency.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 65536,
      pricing: { inputPricePerMillionTokens: 1.50, outputPricePerMillionTokens: 6.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 1600, tokensPerSecond: 75 },
      env: { energyPerMillionTokensWh: 350, carbonGramsPerMillionTokens: 140, confidence: 'medium', source: 'Estimated for compact reasoning tier' },
      tags: ['reasoning', 'math', 'code-debugging'],
      isDefault: false,
    },

    // ---- Anthropic Models ----
    {
      providerKey: 'anthropic',
      modelKey: 'claude-3.5-sonnet',
      providerModelId: 'claude-3-5-sonnet-20241022',
      displayName: 'Claude 3.5 Sonnet',
      family: 'claude-3.5',
      version: '2024-10-22',
      description: 'Premier code architecture and multi-step reasoning champion with exceptional constraint adherence.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 200000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 3.00, outputPricePerMillionTokens: 15.00, cachedInputPerMillionTokensUsd: 0.30, currency: 'USD' },
      performance: { estimatedLatencyMs: 950, tokensPerSecond: 70 },
      env: { energyPerMillionTokensWh: 380, carbonGramsPerMillionTokens: 152, confidence: 'medium', source: 'EMNLP 2024 / Sustainable Computing 2023' },
      tags: ['coding-champion', 'system-architecture', 'vision', 'high-quality'],
      isDefault: true,
    },
    {
      providerKey: 'anthropic',
      modelKey: 'claude-3.5-haiku',
      providerModelId: 'claude-3-5-haiku-20241022',
      displayName: 'Claude 3.5 Haiku',
      family: 'claude-3.5',
      version: '2024-10-22',
      description: 'Ultra-fast, cost-effective model that matches previous-generation flagship performance.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 200000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.80, outputPricePerMillionTokens: 4.00, cachedInputPerMillionTokensUsd: 0.08, currency: 'USD' },
      performance: { estimatedLatencyMs: 380, tokensPerSecond: 110 },
      env: { energyPerMillionTokensWh: 140, carbonGramsPerMillionTokens: 56, confidence: 'medium', source: 'Published Research' },
      tags: ['fast', 'high-efficiency', 'agentic'],
      isDefault: false,
    },
    {
      providerKey: 'anthropic',
      modelKey: 'claude-3.7-sonnet',
      providerModelId: 'claude-3-7-sonnet-20250219',
      displayName: 'Claude 3.7 Sonnet',
      family: 'claude-3.7',
      version: '2025-02-19',
      description: 'Hybrid reasoning model supporting standard generation and extended cognitive thinking.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 200000,
      maxOutputTokens: 64000,
      pricing: { inputPricePerMillionTokens: 3.00, outputPricePerMillionTokens: 15.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 1100, tokensPerSecond: 65 },
      env: { energyPerMillionTokensWh: 420, carbonGramsPerMillionTokens: 168, confidence: 'medium', source: 'Published Research' },
      tags: ['hybrid-thinking', 'extended-reasoning', 'coding-leader'],
      isDefault: false,
    },
    {
      providerKey: 'anthropic',
      modelKey: 'claude-4-sonnet',
      providerModelId: 'claude-4-sonnet',
      displayName: 'Claude 4 Sonnet',
      family: 'claude-4',
      version: '2025-Q2',
      description: 'Next-generation Claude model designed for autonomous workflows and enterprise coding.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 256000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 3.50, outputPricePerMillionTokens: 16.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 900, tokensPerSecond: 80 },
      env: { energyPerMillionTokensWh: 410, carbonGramsPerMillionTokens: 164, confidence: 'low', source: 'Projected Model Energy Profile' },
      tags: ['next-gen', 'frontier', 'enterprise'],
      isDefault: false,
    },
    {
      providerKey: 'anthropic',
      modelKey: 'claude-4-opus',
      providerModelId: 'claude-4-opus',
      displayName: 'Claude 4 Opus',
      family: 'claude-4',
      version: '2025-Q2',
      description: 'Maximum capability frontier model for complex scientific synthesis and nuanced reasoning.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 256000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 15.00, outputPricePerMillionTokens: 75.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 2200, tokensPerSecond: 40 },
      env: { energyPerMillionTokensWh: 880, carbonGramsPerMillionTokens: 352, confidence: 'low', source: 'Projected Opus Tier' },
      tags: ['maximum-intelligence', 'scientific-synthesis'],
      isDefault: false,
    },
    {
      providerKey: 'anthropic',
      modelKey: 'claude-4-haiku',
      providerModelId: 'claude-4-haiku',
      displayName: 'Claude 4 Haiku',
      family: 'claude-4',
      version: '2025-Q2',
      description: 'Ultra-lightweight Claude 4 model engineered for sub-second agentic execution.',
      caps: makeCaps({ reasoning: true, coding: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.60, outputPricePerMillionTokens: 3.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 300, tokensPerSecond: 140 },
      env: { energyPerMillionTokensWh: 120, carbonGramsPerMillionTokens: 48, confidence: 'low', source: 'Projected Haiku Tier' },
      tags: ['ultra-fast', 'agentic'],
      isDefault: false,
    },

    // ---- Google Gemini Models ----
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-1.5-flash',
      providerModelId: 'gemini-1.5-flash',
      displayName: 'Gemini 1.5 Flash',
      family: 'gemini-1.5',
      version: '002',
      description: 'High-frequency multimodal model optimized for low cost, rapid latency, and high context.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true, translation: true }),
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.075, outputPricePerMillionTokens: 0.30, cachedInputPerMillionTokensUsd: 0.01875, currency: 'USD' },
      performance: { estimatedLatencyMs: 320, tokensPerSecond: 150 },
      env: { energyPerMillionTokensWh: 120, carbonGramsPerMillionTokens: 48, confidence: 'medium', source: 'EMNLP 2024 / Sustainable Computing 2023' },
      tags: ['low-cost', 'high-throughput', 'million-context', 'green'],
      isDefault: false,
    },
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-1.5-pro',
      providerModelId: 'gemini-1.5-pro',
      displayName: 'Gemini 1.5 Pro',
      family: 'gemini-1.5',
      version: '002',
      description: 'Massive 2-million-token context champion, superior multilingual analysis and document synthesis.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true, translation: true }),
      contextWindow: 2097152,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 1.25, outputPricePerMillionTokens: 5.00, cachedInputPerMillionTokensUsd: 0.3125, currency: 'USD' },
      performance: { estimatedLatencyMs: 850, tokensPerSecond: 80 },
      env: { energyPerMillionTokensWh: 350, carbonGramsPerMillionTokens: 140, confidence: 'medium', source: 'EMNLP 2024 / Sustainable Computing 2023' },
      tags: ['two-million-context', 'multilingual-leader', 'research-synthesis'],
      isDefault: false,
    },
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-2.0-flash',
      providerModelId: 'gemini-2.0-flash',
      displayName: 'Gemini 2.0 Flash',
      family: 'gemini-2.0',
      version: 'exp',
      description: 'Next-generation multimodal model with native real-time tool calling and high coding capability.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.10, outputPricePerMillionTokens: 0.40, currency: 'USD' },
      performance: { estimatedLatencyMs: 300, tokensPerSecond: 160 },
      env: { energyPerMillionTokensWh: 130, carbonGramsPerMillionTokens: 52, confidence: 'medium', source: 'Published Research' },
      tags: ['next-gen-flash', 'fast', 'real-time'],
      isDefault: false,
    },
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-2.0-flash-lite',
      providerModelId: 'gemini-2.0-flash-lite',
      displayName: 'Gemini 2.0 Flash-Lite',
      family: 'gemini-2.0',
      version: 'preview',
      description: 'Extremely cost-efficient distilled model designed for high-volume enterprise tasks.',
      caps: makeCaps({ reasoning: true, coding: false, toolCalling: true, structuredOutput: true, translation: true }),
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.075, outputPricePerMillionTokens: 0.30, currency: 'USD' },
      performance: { estimatedLatencyMs: 250, tokensPerSecond: 175 },
      env: { energyPerMillionTokensWh: 90, carbonGramsPerMillionTokens: 36, confidence: 'medium', source: 'Published Research' },
      tags: ['cost-saver', 'high-throughput'],
      isDefault: false,
    },
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-2.5-flash',
      providerModelId: 'gemini-2.5-flash',
      displayName: 'Gemini 2.5 Flash',
      family: 'gemini-2.5',
      version: '2025',
      description: 'Upgraded 2.5 architecture balancing sub-second responses with increased reasoning depth.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 1048576,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 0.12, outputPricePerMillionTokens: 0.45, currency: 'USD' },
      performance: { estimatedLatencyMs: 310, tokensPerSecond: 155 },
      env: { energyPerMillionTokensWh: 135, carbonGramsPerMillionTokens: 54, confidence: 'low', source: 'Projected' },
      tags: ['balanced-speed', 'multimodal'],
      isDefault: false,
    },
    {
      providerKey: 'google_gemini',
      modelKey: 'gemini-2.5-pro',
      providerModelId: 'gemini-2.5-pro',
      displayName: 'Gemini 2.5 Pro',
      family: 'gemini-2.5',
      version: '2025',
      description: 'Deep mathematical and algorithmic frontier model with native multimodal audio-visual logic.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, vision: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 2097152,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 1.50, outputPricePerMillionTokens: 6.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 880, tokensPerSecond: 85 },
      env: { energyPerMillionTokensWh: 360, carbonGramsPerMillionTokens: 144, confidence: 'low', source: 'Projected' },
      tags: ['deep-reasoning', 'multimodal-frontier'],
      isDefault: false,
    },

    // ---- Open-Weight & Self-Hosted Models (via OpenAI-Compatible Adapter) ----
    {
      providerKey: 'groq',
      modelKey: 'llama-3.1-8b-instant',
      providerModelId: 'llama-3.1-8b-instant',
      displayName: 'Llama 3.1 8B Instruct',
      family: 'llama-3.1',
      version: '8B',
      description: 'Blazing fast open-weight model running on Groq LPU hardware at 500+ tokens per second.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: false, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.05, outputPricePerMillionTokens: 0.08, currency: 'USD' },
      performance: { estimatedLatencyMs: 120, tokensPerSecond: 520 },
      env: { energyPerMillionTokensWh: 80, carbonGramsPerMillionTokens: 32, confidence: 'high', source: 'Groq LPU Efficiency Data' },
      tags: ['open-weight', 'ultra-fast', 'lpu-accelerated'],
      isDefault: false,
    },
    {
      providerKey: 'groq',
      modelKey: 'llama-3.1-70b-versatile',
      providerModelId: 'llama-3.1-70b-versatile',
      displayName: 'Llama 3.1 70B Instruct',
      family: 'llama-3.1',
      version: '70B',
      description: 'High-capability open-weight model with strong reasoning, instruction following, and multilingual support.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.59, outputPricePerMillionTokens: 0.79, currency: 'USD' },
      performance: { estimatedLatencyMs: 380, tokensPerSecond: 280 },
      env: { energyPerMillionTokensWh: 240, carbonGramsPerMillionTokens: 96, confidence: 'medium', source: 'Groq Energy Profile' },
      tags: ['open-weight', 'high-accuracy', 'versatile'],
      isDefault: false,
    },
    {
      providerKey: 'groq',
      modelKey: 'llama-3.3-70b-versatile',
      providerModelId: 'llama-3.3-70b-versatile',
      displayName: 'Llama 3.3 70B Instruct',
      family: 'llama-3.3',
      version: '70B',
      description: 'State-of-the-art open-weight 70B model matching previous 405B benchmark performance.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, toolCalling: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.59, outputPricePerMillionTokens: 0.79, currency: 'USD' },
      performance: { estimatedLatencyMs: 390, tokensPerSecond: 270 },
      env: { energyPerMillionTokensWh: 250, carbonGramsPerMillionTokens: 100, confidence: 'medium', source: 'Groq Energy Profile' },
      tags: ['open-weight', 'frontier-class', 'cost-effective'],
      isDefault: false,
    },
    {
      providerKey: 'groq',
      modelKey: 'mixtral-8x7b-32768',
      providerModelId: 'mixtral-8x7b-32768',
      displayName: 'Mixtral 8x7B Instruct',
      family: 'mistral',
      version: 'MoE',
      description: 'Sparse mixture-of-experts model activating only 13B parameters per token for high efficiency.',
      caps: makeCaps({ reasoning: true, coding: true, structuredOutput: true }),
      contextWindow: 32768,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.24, outputPricePerMillionTokens: 0.24, currency: 'USD' },
      performance: { estimatedLatencyMs: 250, tokensPerSecond: 380 },
      env: { energyPerMillionTokensWh: 140, carbonGramsPerMillionTokens: 56, confidence: 'high', source: 'Sparse MoE Energy Profile' },
      tags: ['open-weight', 'sparse-moe', 'efficient'],
      isDefault: false,
    },
    {
      providerKey: 'deepseek',
      modelKey: 'deepseek-chat',
      providerModelId: 'deepseek-chat',
      displayName: 'DeepSeek V3',
      family: 'deepseek',
      version: 'V3',
      description: 'Multi-head Latent Attention (MLA) MoE model delivering frontier intelligence at extreme cost efficiency.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 64000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.14, outputPricePerMillionTokens: 0.28, cachedInputPerMillionTokensUsd: 0.014, currency: 'USD' },
      performance: { estimatedLatencyMs: 550, tokensPerSecond: 90 },
      env: { energyPerMillionTokensWh: 160, carbonGramsPerMillionTokens: 64, confidence: 'medium', source: 'DeepSeek MLA Architecture Report' },
      tags: ['open-weight', 'cost-leader', 'coding', 'moe'],
      isDefault: false,
    },
    {
      providerKey: 'deepseek',
      modelKey: 'deepseek-reasoner',
      providerModelId: 'deepseek-reasoner',
      displayName: 'DeepSeek R1',
      family: 'deepseek',
      version: 'R1',
      description: 'Reinforcement-learning driven reasoning model rivaling o1/o3 performance on math and code synthesis.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, structuredOutput: true }),
      contextWindow: 64000,
      maxOutputTokens: 32768,
      pricing: { inputPricePerMillionTokens: 0.55, outputPricePerMillionTokens: 2.19, cachedInputPerMillionTokensUsd: 0.14, currency: 'USD' },
      performance: { estimatedLatencyMs: 2800, tokensPerSecond: 50 },
      env: { energyPerMillionTokensWh: 480, carbonGramsPerMillionTokens: 192, confidence: 'medium', source: 'Published RL Reasoning Study' },
      tags: ['reasoning-leader', 'open-weight', 'rl-reasoner'],
      isDefault: false,
    },
    {
      providerKey: 'together',
      modelKey: 'qwen2.5-72b-instruct',
      providerModelId: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
      displayName: 'Qwen 2.5 72B Instruct',
      family: 'qwen',
      version: '2.5',
      description: 'Top-tier open-weight model with premier coding and mathematical reasoning scores.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, toolCalling: true, structuredOutput: true, longContext: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 1.20, outputPricePerMillionTokens: 1.20, currency: 'USD' },
      performance: { estimatedLatencyMs: 650, tokensPerSecond: 95 },
      env: { energyPerMillionTokensWh: 280, carbonGramsPerMillionTokens: 112, confidence: 'medium', source: 'Published Data' },
      tags: ['open-weight', 'math-specialist', 'coding-specialist'],
      isDefault: false,
    },
    {
      providerKey: 'together',
      modelKey: 'mistral-7b-instruct',
      providerModelId: 'mistralai/Mistral-7B-Instruct-v0.3',
      displayName: 'Mistral 7B Instruct',
      family: 'mistral',
      version: 'v0.3',
      description: 'Compact 7B dense transformer with high instruction following and low memory footprint.',
      caps: makeCaps({ reasoning: true, coding: true, structuredOutput: true }),
      contextWindow: 32768,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.20, outputPricePerMillionTokens: 0.20, currency: 'USD' },
      performance: { estimatedLatencyMs: 250, tokensPerSecond: 160 },
      env: { energyPerMillionTokensWh: 110, carbonGramsPerMillionTokens: 44, confidence: 'high', source: 'Published 7B Benchmarks' },
      tags: ['compact', 'open-weight', 'efficient'],
      isDefault: false,
    },
    {
      providerKey: 'ollama',
      modelKey: 'llama3.1:8b',
      providerModelId: 'llama3.1:8b',
      displayName: 'Llama 3.1 8B (Local)',
      family: 'llama-3.1',
      version: 'Local',
      description: 'Runs entirely on local workstation hardware via Ollama without cloud data transmission.',
      caps: makeCaps({ reasoning: true, coding: true, structuredOutput: true }),
      contextWindow: 32768,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.00, outputPricePerMillionTokens: 0.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 450, tokensPerSecond: 65 },
      env: { energyPerMillionTokensWh: 95, carbonGramsPerMillionTokens: 38, confidence: 'medium', source: 'Local TDP Modeling' },
      tags: ['local', 'zero-cloud-cost', 'private'],
      isDefault: false,
    },

    // ---- Mock Models (10 Diverse Simulation Profiles) ----
    {
      providerKey: 'mock',
      modelKey: 'mock-fast-lowcost',
      providerModelId: 'mock-fast-lowcost',
      displayName: 'Mock Fast Low-Cost',
      family: 'mock',
      version: '1.0',
      description: 'Ultra-fast low-cost simulated model for testing classification, triage, and high-velocity routing.',
      caps: makeCaps({ reasoning: false, coding: false, mathematics: false, structuredOutput: true }),
      contextWindow: 65536,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.05, outputPricePerMillionTokens: 0.15, currency: 'USD' },
      performance: { estimatedLatencyMs: 150, tokensPerSecond: 250 },
      env: { energyPerMillionTokensWh: 60, carbonGramsPerMillionTokens: 24, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'fast', 'low-cost'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-high-reasoning',
      providerModelId: 'mock-high-reasoning',
      displayName: 'Mock High-Quality Reasoning',
      family: 'mock',
      version: '1.0',
      description: 'Simulates frontier-class chain-of-thought logic, formal proofs, and complex decision-making.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 4.00, outputPricePerMillionTokens: 16.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 1800, tokensPerSecond: 45 },
      env: { energyPerMillionTokensWh: 600, carbonGramsPerMillionTokens: 240, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'reasoning', 'high-quality'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-code-architect',
      providerModelId: 'mock-code-architect',
      displayName: 'Mock Code Architect',
      family: 'mock',
      version: '1.0',
      description: 'Simulates full-stack software architecture, TypeScript refactoring, and database schema synthesis.',
      caps: makeCaps({ reasoning: true, coding: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 16384,
      pricing: { inputPricePerMillionTokens: 2.00, outputPricePerMillionTokens: 8.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 700, tokensPerSecond: 90 },
      env: { energyPerMillionTokensWh: 320, carbonGramsPerMillionTokens: 128, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'coding', 'architecture'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-long-context',
      providerModelId: 'mock-long-context',
      displayName: 'Mock Long-Context 1M',
      family: 'mock',
      version: '1.0',
      description: 'Simulates massive 1-million-token document ingestion, cross-chapter analysis, and multi-file search.',
      caps: makeCaps({ reasoning: true, longContext: true, structuredOutput: true }),
      contextWindow: 1000000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 1.00, outputPricePerMillionTokens: 4.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 1100, tokensPerSecond: 75 },
      env: { energyPerMillionTokensWh: 380, carbonGramsPerMillionTokens: 152, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'long-context', 'books-and-codebases'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-vision-multimodal',
      providerModelId: 'mock-vision-multimodal',
      displayName: 'Mock Vision & Multimodal',
      family: 'mock',
      version: '1.0',
      description: 'Simulates visual chart interpretation, UI wireframe analysis, and image-based optical character recognition.',
      caps: makeCaps({ reasoning: true, vision: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 1.50, outputPricePerMillionTokens: 6.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 950, tokensPerSecond: 65 },
      env: { energyPerMillionTokensWh: 450, carbonGramsPerMillionTokens: 180, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'vision', 'multimodal'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-local-openweight',
      providerModelId: 'mock-local-openweight',
      displayName: 'Mock Local Open-Weight',
      family: 'mock',
      version: '1.0',
      description: 'Simulates an on-premise self-hosted cluster with zero cloud ingress/egress costs.',
      caps: makeCaps({ reasoning: true, coding: true }),
      contextWindow: 65536,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.00, outputPricePerMillionTokens: 0.00, currency: 'USD' },
      performance: { estimatedLatencyMs: 500, tokensPerSecond: 80 },
      env: { energyPerMillionTokensWh: 180, carbonGramsPerMillionTokens: 72, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'local', 'private'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-balanced-general',
      providerModelId: 'mock-balanced-general',
      displayName: 'Mock Balanced General-Purpose',
      family: 'mock',
      version: '1.0',
      description: 'General-purpose model balancing latency, cost, and conversational fluency across all standard tasks.',
      caps: makeCaps({ reasoning: true, coding: true, mathematics: true, structuredOutput: true }),
      contextWindow: 128000,
      maxOutputTokens: 8192,
      pricing: { inputPricePerMillionTokens: 0.80, outputPricePerMillionTokens: 3.20, currency: 'USD' },
      performance: { estimatedLatencyMs: 450, tokensPerSecond: 100 },
      env: { energyPerMillionTokensWh: 220, carbonGramsPerMillionTokens: 88, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'balanced', 'general-purpose'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-eco-ultra',
      providerModelId: 'mock-eco-ultra',
      displayName: 'Mock Eco-Optimized Ultra-Green',
      family: 'mock',
      version: '1.0',
      description: 'Engineered for carbon-conscious workloads, achieving the lowest energy footprint in the catalog.',
      caps: makeCaps({ summarization: true, translation: true, structuredOutput: true }),
      contextWindow: 65536,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.10, outputPricePerMillionTokens: 0.25, currency: 'USD' },
      performance: { estimatedLatencyMs: 220, tokensPerSecond: 200 },
      env: { energyPerMillionTokensWh: 35, carbonGramsPerMillionTokens: 14, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'ultra-green', 'lowest-carbon'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-summarizer-compact',
      providerModelId: 'mock-summarizer-compact',
      displayName: 'Mock Summarizer Compact',
      family: 'mock',
      version: '1.0',
      description: 'Specialized for high-compression text condensation, meeting minutes, and executive briefs.',
      caps: makeCaps({ summarization: true }),
      contextWindow: 128000,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.20, outputPricePerMillionTokens: 0.60, currency: 'USD' },
      performance: { estimatedLatencyMs: 260, tokensPerSecond: 150 },
      env: { energyPerMillionTokensWh: 95, carbonGramsPerMillionTokens: 38, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'summarization', 'compact'],
      isDefault: false,
      isMockModel: true,
    },
    {
      providerKey: 'mock',
      modelKey: 'mock-translation-polyglot',
      providerModelId: 'mock-translation-polyglot',
      displayName: 'Mock Translation Polyglot',
      family: 'mock',
      version: '1.0',
      description: 'Specialized for high-fidelity cross-lingual translation across 100+ natural languages.',
      caps: makeCaps({ translation: true }),
      contextWindow: 128000,
      maxOutputTokens: 4096,
      pricing: { inputPricePerMillionTokens: 0.30, outputPricePerMillionTokens: 0.90, currency: 'USD' },
      performance: { estimatedLatencyMs: 300, tokensPerSecond: 130 },
      env: { energyPerMillionTokensWh: 120, carbonGramsPerMillionTokens: 48, confidence: 'high', source: 'Deterministic Mock Engine' },
      tags: ['mock', 'translation', 'polyglot'],
      isDefault: false,
      isMockModel: true,
    },
  ];

  for (const m of modelsData) {
    const providerId = providerMap.get(m.providerKey);
    if (!providerId) continue;

    await prisma.aIModel.upsert({
      where: {
        providerId_modelKey: {
          providerId,
          modelKey: m.modelKey,
        },
      },
      update: {
        providerModelId: m.providerModelId,
        displayName: m.displayName,
        family: m.family,
        version: m.version,
        description: m.description,
        enabled: true,
        available: true,
        isDefault: m.isDefault ?? false,
        isMockModel: m.isMockModel ?? false,
        capabilitiesJson: JSON.stringify(m.caps.capabilities),
        contextWindow: m.contextWindow,
        contextWindowTokens: m.contextWindow,
        maxOutputTokens: m.maxOutputTokens,
        pricingJson: JSON.stringify(m.pricing),
        performanceJson: JSON.stringify(m.performance),
        environmentalMetricsJson: JSON.stringify(m.env),
        tagsJson: JSON.stringify(m.tags),
        status: 'ACTIVE',
      },
      create: {
        providerId,
        modelKey: m.modelKey,
        providerModelId: m.providerModelId,
        displayName: m.displayName,
        family: m.family,
        version: m.version,
        description: m.description,
        enabled: true,
        available: true,
        isDefault: m.isDefault ?? false,
        isMockModel: m.isMockModel ?? false,
        capabilitiesJson: JSON.stringify(m.caps.capabilities),
        contextWindow: m.contextWindow,
        contextWindowTokens: m.contextWindow,
        maxOutputTokens: m.maxOutputTokens,
        pricingJson: JSON.stringify(m.pricing),
        performanceJson: JSON.stringify(m.performance),
        environmentalMetricsJson: JSON.stringify(m.env),
        tagsJson: JSON.stringify(m.tags),
        status: 'ACTIVE',
      },
    });
  }

  console.log(`  ✓ Created/updated ${modelsData.length} AI models across all providers`);
  console.log('✅ Model catalog seeding complete!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
